print ("Reglas de The Club Simpson")
print ("1. Ser necesita un número de jugadores 2-4 personas")
print ("2. Cada jugador elige un personaje y coloca su ficha en la casilla de inicio")
print ("3. Tira un dado para determinar cuántas casillas puedes mover")
print ("4. Mueve tu ficha según el número del dado")
print ("5. Entra  a alguna casa y manda al estado a alguien (pidele que te muestre una carta de su mazo)")
print ("5. Sigue las instrucciones de la casilla (donuts, trabajo, problemas)")
print ("6. Preguntas y desafíos responde correctamente para avanzar")
print ("7. Llegada a la meta el primer jugador que llega a la casa de los Simpson gana")
print ("8. Colisiones realiza un mini-juego o desafío para determinar quién sigue avanzando")
print ("9. Fin del juego el juego termina cuando un jugador llega a la meta")