print("Persona: ¡Hola, michi!")
print("Gato: Miau")
print("")
print("Persona: ¿Tienes hambre?")
print("Gato: Miau miau (¡Sí, mucho!)")
print("")
print("Persona: Está bien, vamos a comer.")
print("Gato: Miau~ (Gracias, humano)")
print("")
print("Persona: Hasta luego, michi.")
print("Gato: Miau.")
